-- Estados+Cidades:
-- Rio de Janeiro (RJ)
INSERT INTO ESTADO (nome, sigla) VALUES ('Rio de Janeiro', 'RJ');       -- ID: 1
INSERT INTO CIDADE (ESTADO_ID, NOME) VALUES (1,'Rio de Janeiro');   -- ID: 1
-- São Paulo (SP)
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('São Paulo', 'SP');        -- ID: 2
INSERT INTO CIDADE (ESTADO_ID, NOME) VALUES (2,'São Paulo');    -- ID: 2
-- Tocantins (TO)
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('Tocantins', 'TO');    -- ID: 3
INSERT INTO CIDADE (ESTADO_ID, NOME) VALUES ( 3,'Palmas');  -- ID: 3


--Crinado Endereços
INSERT INTO ENDERECO (NUMERO, CIDADE_ID, BAIRRO, CEP, COMPLEMENTO, LOGRADOURO) VALUES (1000,1, 'Copacabana','99999-999','Avenida','Atlântica' );            -- ID: 1
INSERT INTO ENDERECO (NUMERO, CIDADE_ID, BAIRRO, CEP, COMPLEMENTO, LOGRADOURO) VALUES (1578,2, 'Bela Vista','99999-999','Avenida','Paulista' );             -- ID: 2
INSERT INTO ENDERECO (NUMERO, CIDADE_ID, BAIRRO, CEP, COMPLEMENTO, LOGRADOURO) VALUES (6,3, 'Plano Diretor Norte', '77000-000','Quadra','110, Alameda 08'); -- ID: 3


-- Roles de Usuário
INSERT INTO ROLE (TIPO_USUARIO) VALUES ('ROLE_ADMINISTRADOR');      --ID: 1
INSERT INTO ROLE (TIPO_USUARIO) VALUES (' ROLE_USUARIO');           --ID: 2

--Inserindo Usuários:
INSERT INTO USUARIO (EMAIL, SENHA) VALUES ('joao@email.com','$2a$10$yyEv.yZ0D8wk/p7PNqHoPuNJTgjJ3P8.Rt2g8FF3aMMAC6PcYSHWi'); --ID: 1
INSERT INTO USUARIO (EMAIL,SENHA) VALUES ('maria@email.com','$2a$10$yyEv.yZ0D8wk/p7PNqHoPuNJTgjJ3P8.Rt2g8FF3aMMAC6PcYSHWi'); --ID: 2
INSERT INTO USUARIO (EMAIL,SENHA) VALUES ('caio@email.com','$2a$10$yyEv.yZ0D8wk/p7PNqHoPuNJTgjJ3P8.Rt2g8FF3aMMAC6PcYSHWi');  --ID: 3

--Inserindo Pessoas
INSERT INTO PESSOA (ENDERECO_ID, USUARIO_ID, NOME, SOBRENOME, CPF, TELEFONE) VALUES (1,1,'João','Silva', '932.934.957-96','21 9 9999-9999');      --ID: 1
INSERT INTO PESSOA (ENDERECO_ID, USUARIO_ID, NOME, SOBRENOME, CPF, TELEFONE) VALUES (2,2,'Maria','Silva', '882.457.728-87','11 9 9999-9999');     --ID: 2
INSERT INTO PESSOA (ENDERECO_ID, USUARIO_ID, NOME, SOBRENOME, CPF, TELEFONE) VALUES (3,3,'Caio','Silva', '759.649.631-88','63 9 9999-9999');      --ID: 3


-- ATRIBUIÇÃO DE PESSOA - TIPAGEM:
INSERT INTO CLIENTE (ID) VALUES (1); -- ID: 1
INSERT INTO CLIENTE (ID) VALUES (2); -- ID: 2
INSERT INTO PRESTADOR (ID, CNPJ, RAZAO_SOCIAL) VALUES (3,'15.514.929/0001-06', 'Caio Barbeiro'); -- ID: 3

-- Configuração das Roles
INSERT INTO USUARIO_ROLES (ROLES_ID, USUARIO_ID) VALUES ( 1,3); --ID: 1
INSERT INTO USUARIO_ROLES (ROLES_ID, USUARIO_ID) VALUES (2,1);  --ID: 2
INSERT INTO USUARIO_ROLES (ROLES_ID, USUARIO_ID) VALUES (2,2);  --ID: 3

--SERVICO:
INSERT INTO SERVICO (PRECO, DESCRICAO, PRESTADOR_ID) VALUES (40,'Corte de Cabelo',3);       --ID: 1
INSERT INTO SERVICO (PRECO, DESCRICAO, PRESTADOR_ID) VALUES (40,'Corte de Barba',3);        --ID: 2
INSERT INTO SERVICO (PRECO, DESCRICAO, PRESTADOR_ID) VALUES (40,'Corte de Sobrancelha',3);  --ID: 3

-- DISPONIBILIDADE:
INSERT INTO DISPONIBILIDADE (DATA_INICIO, DATA_FIM, HORA_INICIO, HORA_FIM, TEMPO_ATENDIMENTO, ESTA_ATIVO, PRESTADOR_ID) VALUES ( '2025-11-01','2025-11-30','08:00:00','18:00:00',60,TRUE,3); --ID: 1

-- AGENDAMENTO:
INSERT INTO AGENDA (DATA_HORA_AGENDAMENTO, STATUS_AGENDAMENTO, CLIENTE_ID, PRESTADOR_ID) VALUES ('2025-11-03 14:00:00', 'AGENDADO',1,3); -- ID:1
INSERT INTO AGENDA (DATA_HORA_AGENDAMENTO, STATUS_AGENDAMENTO, CLIENTE_ID, PRESTADOR_ID) VALUES ('2025-11-03 17:00:00', 'AGENDADO',1,3); -- ID:2


-- ATENDIMENTO:
INSERT INTO ATENDIMENTO (AGENDAMENTO_ID, DATA_HORA_ATENDIMENTO, OBSERVACAO, CLIENTE_ID, PRESTADOR_ID) VALUES (1,'2025-11-03 14:00:00', '',1,3);    -- ID:1
INSERT INTO ATENDIMENTO (AGENDAMENTO_ID, DATA_HORA_ATENDIMENTO, OBSERVACAO, CLIENTE_ID, PRESTADOR_ID) VALUES (2,'2025-11-03 15:00:00', '',2,3);    -- ID:2

-- Associando Serviço ao Atendimento
INSERT INTO ATENDIMENTO_SERVICOS (ATENDIMENTO_ID, SERVICOS_ID) VALUES (1,1);
INSERT INTO ATENDIMENTO_SERVICOS (ATENDIMENTO_ID, SERVICOS_ID) VALUES (1,2);

INSERT INTO ATENDIMENTO_SERVICOS (ATENDIMENTO_ID, SERVICOS_ID) VALUES (2,2);