-- Estados+Cidades:
-- Rio de Janeiro (RJ)
INSERT INTO ESTADO (nome, sigla) VALUES ('Rio de Janeiro', 'RJ');       -- ID: 1
INSERT INTO CIDADE (ESTADO_ID, NOME) VALUES (1,'Rio de Janeiro');   -- ID: 1
-- São Paulo (SP)
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('São Paulo', 'SP');        -- ID: 2
INSERT INTO CIDADE (ESTADO_ID, NOME) VALUES (2,'São Paulo');    -- ID: 2
-- Tocantins (TO)
INSERT INTO ESTADO (NOME, SIGLA) VALUES ('Tocantins', 'TO');    -- ID: 3
INSERT INTO CIDADE (ESTADO_ID, NOME) VALUES ( 3,'Palmas');  -- ID: 3


--Crinado Endereços
INSERT INTO ENDERECO (NUMERO, CIDADE_ID, BAIRRO, CEP, COMPLEMENTO, LOGRADOURO) VALUES (1000,1, 'Copacabana','99999-999','Avenida','Atlântica' );            -- ID: 1
INSERT INTO ENDERECO (NUMERO, CIDADE_ID, BAIRRO, CEP, COMPLEMENTO, LOGRADOURO) VALUES (1578,2, 'Bela Vista','99999-999','Avenida','Paulista' );             -- ID: 2
INSERT INTO ENDERECO (NUMERO, CIDADE_ID, BAIRRO, CEP, COMPLEMENTO, LOGRADOURO) VALUES (6,3, 'Plano Diretor Norte', '77000-000','Quadra','110, Alameda 08'); -- ID: 3


-- Roles de Usuário
INSERT INTO ROLE (TIPO_USUARIO) VALUES ('ROLE_ADMINISTRADOR');      --ID: 1
INSERT INTO ROLE (TIPO_USUARIO) VALUES (' ROLE_USUARIO');           --ID: 2

--Inserindo Usuários:
INSERT INTO USUARIO (EMAIL, SENHA) VALUES ('joao@email.com','$2a$10$yyEv.yZ0D8wk/p7PNqHoPuNJTgjJ3P8.Rt2g8FF3aMMAC6PcYSHWi'); --ID: 1
INSERT INTO USUARIO (EMAIL,SENHA) VALUES ('maria@email.com','$2a$10$yyEv.yZ0D8wk/p7PNqHoPuNJTgjJ3P8.Rt2g8FF3aMMAC6PcYSHWi'); --ID: 2
INSERT INTO USUARIO (EMAIL,SENHA) VALUES ('caio@email.com','$2a$10$yyEv.yZ0D8wk/p7PNqHoPuNJTgjJ3P8.Rt2g8FF3aMMAC6PcYSHWi');  --ID: 3

--Inserindo Pessoas
INSERT INTO PESSOA (ENDERECO_ID, USUARIO_ID, NOME, SOBRENOME, TELEFONE) VALUES (1,1,'João','Silva', '21 9 9999-9999');      --ID: 1
INSERT INTO PESSOA (ENDERECO_ID, USUARIO_ID, NOME, SOBRENOME, TELEFONE) VALUES (2,2,'Maria','Silva', '11 9 9999-9999');     --ID: 2
INSERT INTO PESSOA (ENDERECO_ID, USUARIO_ID, NOME, SOBRENOME, TELEFONE) VALUES (3,3,'Caio','Silva', '63 9 9999-9999');      --ID: 3

-- ATRIBUIÇÃO DE PESSOA - TIPAGEM:

-- Configuração das Roles
INSERT INTO USUARIO_ROLES (ROLES_ID, USUARIO_ID) VALUES ( 1,3); --ID: 1
INSERT INTO USUARIO_ROLES (ROLES_ID, USUARIO_ID) VALUES (2,1);  --ID: 2
INSERT INTO USUARIO_ROLES (ROLES_ID, USUARIO_ID) VALUES (2,2);  --ID: 3

--SERVICO - FALTA DEFINIR AS TIPAGENS DE PESSOA PARA PODER FAZER A ATRIBUIÇÃO:
INSERT INTO SERVICO (PRECO, DESCRICAO) VALUES (40,'Corte de Cabelo');       --ID: 1
INSERT INTO SERVICO (PRECO, DESCRICAO) VALUES (40,'Corte de Barba');        --ID: 2
INSERT INTO SERVICO (PRECO, DESCRICAO) VALUES (40,'Corte de Sobrancelha');  --ID: 3

-- DISPONIBILIDADE - FALTA DEFINIR AS TIPAGENS DE PESSOA PARA PODER FAZER A ATRIBUIÇÃO:
INSERT INTO DISPONIBILIDADE (DATA_INICIO, DATA_FIM, HORA_INICIO, HORA_FIM, TEMPO_ATENDIMENTO, ESTA_ATIVO) VALUES ( '2025-11-01','2025-11-30','08:00:00','18:00:00',60,TRUE); --ID: 1

-- AGENDAMENTO - FALTA DEFINIR AS TIPAGENS DE PESSOA PARA PODER FAZER A ATRIBUIÇÃO:
INSERT INTO AGENDA (DATA_HORA_AGENDAMENTO, STATUS_AGENDAMENTO) VALUES ('2025-11-03 14:00:00', 'AGENDADO'); -- ID:1
INSERT INTO AGENDA (DATA_HORA_AGENDAMENTO, STATUS_AGENDAMENTO) VALUES ('2025-11-03 17:00:00', 'AGENDADO'); -- ID:2


-- ATENDIMENTO - FALTA DEFINIR AS TIPAGENS DE PESSOA PARA PODER FAZER A ATRIBUIÇÃO:
INSERT INTO ATENDIMENTO (AGENDAMENTO_ID, DATA_HORA_ATENDIMENTO, OBSERVACAO) VALUES (1,'2025-11-03 14:00:00', '');    -- ID:1
INSERT INTO ATENDIMENTO (AGENDAMENTO_ID, DATA_HORA_ATENDIMENTO, OBSERVACAO) VALUES (2,'2025-11-03 15:00:00', '');    -- ID:2

-- Associando Serviço ao Atendimento
INSERT INTO ATENDIMENTO_SERVICOS (ATENDIMENTO_ID, SERVICOS_ID) VALUES (1,1);
INSERT INTO ATENDIMENTO_SERVICOS (ATENDIMENTO_ID, SERVICOS_ID) VALUES (1,2);

INSERT INTO ATENDIMENTO_SERVICOS (ATENDIMENTO_ID, SERVICOS_ID) VALUES (2,2);